package: events
version: '5.0.2'
author: 'Alexander Walther'
supportpage: https://alexplusde.github.io/events/

requires:
    php:
        version: '>8.1'
    redaxo: '^5.17'
    packages:
        auto_delete: ">=1"
        yform: "^4"
        yform_geo_osm: ^1
        yform_field: "^2"


page:
    title: translate:events
    prio: 100
    icon: rex-icon fa-calendar-days

pages:
    events:
        title: translate:events
        main: true
        block: system
        prio: 15
        icon: rex-icon fa-calendar-day
        perm: events[]
        subpages: 
            calendar:
                title: translate:event_calendar
                icon: rex-icon fa-calendar-days
                perm: events[calendar]
            date_lang:
                title: translate:event_lang
                perm: events[date_lang]
                icon: rex-icon fa-language
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_date_lang
                    wrapper_class: rex_event_date_lang
                    show_title: false
            date:
                title: translate:event_date
                icon: rex-icon fa-calendar-day
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_date
                    wrapper_class: rex_event_date
                    show_title: false
                perm: events[date]
            category:
                title: translate:event_category
                icon: rex-icon fa-folder
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_category
                    wrapper_class: rex_event_category
                    show_title: false
                perm: events[category]
            location:
                title: translate:event_location
                icon: rex-icon fa-map-marker
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_location
                    wrapper_class: rex_event_location
                    show_title: false
                perm: events[location]
            registration:
                title: translate:event_date_registration
                icon: rex-icon fa-users-between-lines
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_date_registration
                    wrapper_class: rex_event_date_registration
                    show_title: false
                perm: events[register]
            registration_person:
                title: translate:event_date_registration_person
                icon: rex-icon fa-user-plus
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_date_registration_person
                    wrapper_class: rex_event_date_registration_person
                    show_title: false
                perm: events[registration_person]
            category_request:
                title: translate:event_category_request
                icon: rex-icon fa-person-circle-question
                subPath: pages/data_edit.php
                yform:
                    table_name: rex_event_category_request
                    wrapper_class: rex_event_category_request
                    show_title: false
                perm: events[request]
            settings:
                title: translate:event_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:event_docs
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: events[docs]
                pjax: false

default_config:
    currency: EUR
    timezone_api_code: ''
    default_organizer_name: ''
    fallback_image: 'events_fallback_image.jpg'
    editor: "form-control redactor-editor--default"
    event_empty: "<p>Keine Veranstaltungen gefunden.</p>"
    withdrawal: ''
    article_id: ''
    url_profile: false # Merkt sich, ob URL-Profile bereits installiert wurden
