package: events
version: '3.0.0-dev5'
author: 'Alexander Walther'
supportpage: https://alexplusde.github.io/events/
load: late

requires:
    php:
        version: '>7.3'
    redaxo: ^5.12
    packages:
        yform: ">=4"
        yform_geo_osm: ^1.2.1
        yform_field: '>1'


page:
    title: translate:events
    prio: 100
    icon: rex-icon fa-gear

pages:
    events:
        title: translate:events
        main: true
        block: system
        prio: 15
        icon: rex-icon fa-calendar
        perm: events[]
        subpages: 
            calendar:
                title: Übersicht
                icon: rex-icon fa-calendar
                perm: events[calendar]
            date_lang:
                title: translate:events_lang
                perm: events[date_lang]
                icon: rex-icon fa-flag
                subPath: pages/data_edit.php
                yformTable: rex_event_date_lang
                yformClass: rex_event_date_lang
                yformTitle: false
            date:
                title: Termine
                icon: rex-icon fa-calendar-o
                subPath: pages/data_edit.php
                yformTable: rex_event_date
                yformClass: rex_event_date
                yformTitle: false
                perm: events[date]
            category:
                title: Kategorien
                icon: rex-icon fa-folder
                subPath: pages/data_edit.php
                yformTable: rex_event_category
                yformClass: rex_event_category
                yformTitle: false
                perm: events[category]
            location:
                title: Location
                icon: rex-icon fa-map-marker
                subPath: pages/data_edit.php
                yformTable: rex_event_location
                yformClass: rex_event_location
                yformTitle: false
                perm: events[location]
            registration:
                title: Anmeldungen
                icon: rex-icon rex-icon-user
                subPath: pages/data_edit.php
                yformTable: rex_event_date_registration
                yformClass: rex_event_date_registration
                yformTitle: false
                perm: events[register]
            registration_person:
                title: Teilnehmende
                icon: rex-icon rex-icon-user
                subPath: pages/data_edit.php
                yformTable: rex_event_date_registration_person
                yformClass: rex_event_date_registration_person
                yformTitle: false
                perm: events[registration_person]
            request:
                title: Anfragen
                icon: rex-icon rex-icon-user
                subPath: pages/data_edit.php
                yformTable: rex_event_category_request
                yformClass: rex_event_category_request
                yformTitle: false
                perm: events[request]
            settings:
                title: Settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: Docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: events[docs]

default_config:
    currency: EUR
